"""E-Book Export tool for Story Alternator."""

import uuid
from google.cloud import storage

BUCKET_NAME = "story-alternator-media-qwiklabs-gcp-02-f255a355adec"
PROJECT_ID = "qwiklabs-gcp-02-f255a355adec"


def export_story_ebook(
    story_title: str, author: str, content: str, format_type: str = "html"
) -> str:
    """Exports an altered story branch into a beautifully styled e-book document and returns a public HTTPS download link.

    Args:
        story_title: Title of the story or book.
        author: Author name or original creator.
        content: The text of the altered story branch or rewritten chapters.
        format_type: Document format ('html', 'md', 'txt').

    Returns:
        Public HTTPS URL to download the e-book artifact.
    """
    filename = f"ebook_{uuid.uuid4().hex[:8]}.{format_type}"
    
    if format_type.lower() == "html":
        ebook_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{story_title} - Alternate Edition</title>
    <style>
        body {{
            font-family: 'Georgia', serif;
            line-height: 1.8;
            max-width: 800px;
            margin: 40px auto;
            padding: 0 20px;
            background-color: #faf8f5;
            color: #2c2c2c;
        }}
        h1 {{
            font-family: 'Cinzel', serif;
            text-align: center;
            color: #1a1a2e;
            margin-bottom: 5px;
        }}
        .byline {{
            text-align: center;
            font-style: italic;
            color: #666;
            margin-bottom: 40px;
        }}
        .content {{
            white-space: pre-wrap;
            font-size: 18px;
        }}
        .footer {{
            margin-top: 60px;
            border-top: 1px solid #ddd;
            padding-top: 20px;
            text-align: center;
            font-size: 13px;
            color: #888;
        }}
    </style>
</head>
<body>
    <h1>{story_title}</h1>
    <div class="byline">Originally by {author} • Generated by Story Alternator</div>
    <div class="content">{content}</div>
    <div class="footer">Enterprise Book Reading & Story Alternation Platform</div>
</body>
</html>"""
        content_type = "text/html"
    else:
        ebook_content = f"# {story_title}\nBy {author}\n\n{content}"
        content_type = "text/plain"

    try:
        client = storage.Client(project=PROJECT_ID)
        bucket = client.bucket(BUCKET_NAME)
        blob = bucket.blob(f"ebooks/{filename}")
        blob.upload_from_string(ebook_content, content_type=content_type)
        
        public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/ebooks/{filename}"
        return f"📖 E-Book successfully exported! Download link: {public_url}"
    except Exception as e:
        return f"Export created locally, upload notice: {e}. Content preview:\n{content[:200]}..."
